### ISSUE TITLE
Exclude files from coverage

### ISSUE THREAD

**Issue by mattgen88** [gotwarlost/istanbul#118]
I'd like to see the ability to exclude files from coverage. 

The use case is some 3rd party code that is embedded in other code (minified plugins).

I'd like to be able to either exclude blocks of code, or the entire file.

**Comment by wayneseymour** [comment]
@gotwarlost what should we store in the `.istanbul.yml` file so we dont have to do it on the cli?

**Comment by gaballard** [comment]
@gotwarlost: +1 for an exclusion option to add to `.istanbul.yml`. Seems like a major oversight if such an option doesn't exist.

**Comment by jcollum** [comment]
there is an excludes portion in the yml file: 

```
instrumentation:
    root: .
    extensions:
        - .js
    default-excludes: true
    excludes: []
```

But it doesn't seem to do what we want, I tried excluding my samples and etc folders: 

```
instrumentation:
  excludes: ['**/samples/**', '**/etc/**']
```

but it's still reporting coverage for code in those folders. 

Same for `-x`: 

```
./node_modules/.bin/istanbul cover -x 'etc' -x 'sample'
``` 

Still reporting coverage for code in those folders.

**Comment by climboid** [comment]
+1 @jcollum I'm having exactly the same problem. Can't find documentation anywhere on how to populate the excludes. Have tried everything so far and I still get the lcov-report/index.html file show unneeded files

**Comment by jcollum** [comment]
@gotwarlost Seems like this issue is not actually resolved. Or the docs are unclear on how to actually use the excludes feature.

**Comment by climboid** [comment]
I've managed to exclude file extensions but not directiores.

**Comment by Roam-Cooper** [comment]
Seems to completely ignore the -x command line option for me, too...

**Comment by Roam-Cooper** [comment]
What the hell does:

```-x <exclude-pattern> [-x <exclude-pattern>]
              one or more fileset patterns e.g. "**/vendor/**"```

Even mean?

I can exclude with ```-x "**/folder/**"``` now, but I cannot figure out how to exclude multiple as the help is not clear about it in the slightest...

**Comment by gotwarlost** [comment]
You can pass in multiple `-x pattern` directives

**Comment by Ehesp** [comment]
@jcollum Late to the party, but thats not how you do arrays in yml:

```yml
instrumentation:
    root: .
    extensions:
        - .js
    default-excludes: true
    excludes:
        - src/utils.js

```

**Comment by jcollum** [comment]
@Ehesp I think you should read the docs: http://yaml.org/spec/1.0/ section A.1. Sequence

**Comment by sfyfe31** [comment]
I got this working as follows
`istanbul cover -x "mocha-test/*.js" -x "mocha-test/**/*.js" -x "api/hooks/*.js" -x "api/responses/*.js"`

**Comment by frankgreco** [comment]
@jcollum It's the double quotes that did it for me. Single quotes worked just fine:

```yml
instrumentation:
    root: .
    extensions:
        - .js
    default-excludes: true
    excludes: ['*-spec.js', '**/mock/**']
```

Hope this helps
