### ISSUE TITLE
include-pid in YAML configuration not observed

### ISSUE THREAD

**Issue by mpareja** [gotwarlost/istanbul#401]
The following `.istanbul.yml` file does not generate coverage files with PIDs in the filename. When I specify the --include-pid command line parameter, things work just fine. Oddly enough, verbose mode shows that the include-pid value is being parsed correctly as true - it just isn't being used.

```
verbose: true
check:
    global:
        statements: 100
        lines: 100
        branches: 100
        functions: 100

instrumentation:
    excludes:
        - "gulpfile.js"
        - "config.js"
        - "**/public/**"
    include-all-sources: true
    include-pid: true

reporting:
    dir: "../coverage"
```
