### ISSUE TITLE
Document check-coverage thresholds usage

### ISSUE THREAD

**Issue by MattiSG** [gotwarlost/istanbul#479]
If I use the following `.istanbul.yml` file:

```yaml
check:
	global:
		statements: 90
		lines: 90
		branches: 90
		functions: 90
```

then I never get a fail, even though my coverage is 70%.

However, if I run `istanbul check-coverage --statements 90` then the test fails as expected.

I discovered this usage only thanks to #192. It seems important to document the usage of `check-coverage` (and possibly fix the YAML config loading, but I'm not sure I understood it properly…).

**Comment by gotwarlost** [comment]
Are you actually running the `check-coverage` command when you use the istanbul.yml file? 

Note that setting the thresholds does not automatically run the check coverage command for you. It only makes it easier to put all your thresholds in one place.

**Comment by MattiSG** [comment]
Thanks for providing this information. I understood this on my own after some time. The main issue here is really about documenting the feature usage.

**Comment by niftylettuce** [comment]
why is this still not documented?

**Comment by niftylettuce** [comment]
```yml
check-coverage:
  statements: 50,
  branches: 50
```

doesn't work

```yml
reporting:
  check-coverage:
    statements: 50,
    branches: 50
```

doesn't work

what's the proper syntax?

**Comment by niftylettuce** [comment]
```yml
check:
    global:
        branches: 100
        functions: 100
        lines: 100
        statements: 100
```

Works!  Make sure file is `.istanbul.yml` and not `istanbul.yml` as well.
