### ISSUE TITLE
Two reports in separate directories?

### ISSUE THREAD

**Issue by bgannonPL** [gotwarlost/istanbul#509]
I'm trying to generate a cobertura report and an html report in separate directories, e.g. /coverage/cobertura and /coverage/html. (This is how I set things up via Karma, and I'm trying to get the same report structure on a node/tape project.) I haven't been able to get there with a config file or with command line arguments, and would prefer to avoid using instanbul as a library as it will mean more time/energy. 

Using report-config in a config file I was able to get the cobertura file into a separate directory with 'file: cobertura/cobertura.xml', but it doesn't seem possible to configure the html report destination the same way (which sort of makes sense given that html reports aren't a single file, but hopefully there's an equivalent). Have I overlooked something? Or do I need to resort to using istanbul as a lib and generating reports programmatically?

**Comment by gotwarlost** [comment]
Use `subdir: foo` for the html report. I'm still in the middle of documenting all the changes and I have lost context after a few weeks of vacation :) Let me know if that works.

**Comment by bgannonPL** [comment]
@gotwarlost Not working for me, but I'm new to Istanbul, maybe I've overlooked something? Here are the contents of my .istanbul.yaml file:  
```
reporting:
    reports:
        - html
        - cobertura
    report-config:
        html:
            subdir: html
        cobertura:
            file: cobertura/cobertura.xml
```

The reporting directory is specified as a command line argument. Cobertura ends up in a subdirectory, but the HTML report is in the reporting directory, not in a subdir.
