### ISSUE TITLE
Unexpected token %

### ISSUE THREAD

**Issue by stenrap** [gotwarlost/istanbul#522]
We just began using istanbul for code coverage and we really like it. Unfortunately, however, we can't get it to work on our Jenkins server. This is the `.istanbul.yml` file in the root of our project...

```
verbose: false
instrumentation:
    root: .
    extensions:
        - .js
    default-excludes: true
    excludes: ['**/tinymce/**', '**/js/libraries/**', '**/tools/**', '*-translations.js', '*.bundle.js']
    embed-source: false
    variable: __coverage__
    compact: true
    preserve-comments: false
    complete-copy: false
    save-baseline: false
    baseline-file: ./coverage/coverage-baseline.json
    include-all-sources: true
    include-pid: false
    es-modules: false
reporting:
    print: summary
    reports:
        - lcov
    dir: ./tools/coverage
    watermarks:
        statements: [50, 80]
        lines: [50, 80]
        functions: [50, 80]
        branches: [50, 80]
    report-config:
        clover: {file: clover.xml}
        cobertura: {file: cobertura-coverage.xml}
        json: {file: coverage-final.json}
        json-summary: {file: coverage-summary.json}
        lcovonly: {file: lcov.info}
        teamcity: {file: null, blockName: Code Coverage Summary}
        text: {file: null, maxCols: 0}
        text-lcov: {file: lcov.info}
        text-summary: {file: null}
hooks:
    hook-run-in-context: false
    post-require-hook: null
    handle-sigint: false
check:
    global:
        statements: 0
        lines: 0
        branches: 0
        functions: 0
        excludes: []
    each:
        statements: 0
        lines: 0
        branches: 0
        functions: 0
        excludes: []
```

...and we're executing this command (which is successful on our development machines):

`istanbul cover _mocha -- --require ./test/setup.js --recursive`

The unit tests execute successfully on our Jenkins server, but istanbul then fails with this:

```
/usr/lib/node_modules/istanbul/node_modules/esprima/esprima.js:5703
            throw e;
            ^
Error: Line 1: Unexpected token %
    at constructError (/usr/lib/node_modules/istanbul/node_modules/esprima/esprima.js:2405:21)
    at createError (/usr/lib/node_modules/istanbul/node_modules/esprima/esprima.js:2424:17)
    at unexpectedTokenError (/usr/lib/node_modules/istanbul/node_modules/esprima/esprima.js:2498:13)
    at throwUnexpectedToken (/usr/lib/node_modules/istanbul/node_modules/esprima/esprima.js:2503:15)
    at parsePrimaryExpression (/usr/lib/node_modules/istanbul/node_modules/esprima/esprima.js:3305:13)
    at inheritCoverGrammar (/usr/lib/node_modules/istanbul/node_modules/esprima/esprima.js:2679:18)
    at parseLeftHandSideExpressionAllowCall (/usr/lib/node_modules/istanbul/node_modules/esprima/esprima.js:3412:20)
    at inheritCoverGrammar (/usr/lib/node_modules/istanbul/node_modules/esprima/esprima.js:2679:18)
    at parsePostfixExpression (/usr/lib/node_modules/istanbul/node_modules/esprima/esprima.js:3488:16)
    at parseUnaryExpression (/usr/lib/node_modules/istanbul/node_modules/esprima/esprima.js:3548:20)
    at inheritCoverGrammar (/usr/lib/node_modules/istanbul/node_modules/esprima/esprima.js:2679:18)
    at parseBinaryExpression (/usr/lib/node_modules/istanbul/node_modules/esprima/esprima.js:3637:16)
    at inheritCoverGrammar (/usr/lib/node_modules/istanbul/node_modules/esprima/esprima.js:2679:18)
    at parseConditionalExpression (/usr/lib/node_modules/istanbul/node_modules/esprima/esprima.js:3694:16)
    at parseAssignmentExpression (/usr/lib/node_modules/istanbul/node_modules/esprima/esprima.js:3891:16)
    at isolateCoverGrammar (/usr/lib/node_modules/istanbul/node_modules/esprima/esprima.js:2661:18)
    at parseExpression (/usr/lib/node_modules/istanbul/node_modules/esprima/esprima.js:3940:16)
    at parseStatement (/usr/lib/node_modules/istanbul/node_modules/esprima/esprima.js:4797:16)
    at parseStatementListItem (/usr/lib/node_modules/istanbul/node_modules/esprima/esprima.js:3987:16)
    at parseStatementList (/usr/lib/node_modules/istanbul/node_modules/esprima/esprima.js:3996:23)
    at parseBlock (/usr/lib/node_modules/istanbul/node_modules/esprima/esprima.js:4007:17)
    at parseStatement (/usr/lib/node_modules/istanbul/node_modules/esprima/esprima.js:4748:20)
    at parseStatementListItem (/usr/lib/node_modules/istanbul/node_modules/esprima/esprima.js:3987:16)
    at parseFunctionSourceElements (/usr/lib/node_modules/istanbul/node_modules/esprima/esprima.js:4869:23)
    at parseFunctionExpression (/usr/lib/node_modules/istanbul/node_modules/esprima/esprima.js:5075:16)
    at parsePrimaryExpression (/usr/lib/node_modules/istanbul/node_modules/esprima/esprima.js:3271:24)
    at inheritCoverGrammar (/usr/lib/node_modules/istanbul/node_modules/esprima/esprima.js:2679:18)
    at parseLeftHandSideExpressionAllowCall (/usr/lib/node_modules/istanbul/node_modules/esprima/esprima.js:3412:20)
    at inheritCoverGrammar (/usr/lib/node_modules/istanbul/node_modules/esprima/esprima.js:2679:18)
    at parsePostfixExpression (/usr/lib/node_modules/istanbul/node_modules/esprima/esprima.js:3488:16)
    at parseUnaryExpression (/usr/lib/node_modules/istanbul/node_modules/esprima/esprima.js:3548:20)
    at inheritCoverGrammar (/usr/lib/node_modules/istanbul/node_modules/esprima/esprima.js:2679:18)
    at parseBinaryExpression (/usr/lib/node_modules/istanbul/node_modules/esprima/esprima.js:3637:16)
    at inheritCoverGrammar (/usr/lib/node_modules/istanbul/node_modules/esprima/esprima.js:2679:18)
    at parseConditionalExpression (/usr/lib/node_modules/istanbul/node_modules/esprima/esprima.js:3694:16)
    at parseAssignmentExpression (/usr/lib/node_modules/istanbul/node_modules/esprima/esprima.js:3891:16)
    at inheritCoverGrammar (/usr/lib/node_modules/istanbul/node_modules/esprima/esprima.js:2679:18)
    at parseGroupExpression (/usr/lib/node_modules/istanbul/node_modules/esprima/esprima.js:3160:16)
    at inheritCoverGrammar (/usr/lib/node_modules/istanbul/node_modules/esprima/esprima.js:2679:18)
    at parsePrimaryExpression (/usr/lib/node_modules/istanbul/node_modules/esprima/esprima.js:3237:20)
    at inheritCoverGrammar (/usr/lib/node_modules/istanbul/node_modules/esprima/esprima.js:2679:18)
    at parseLeftHandSideExpressionAllowCall (/usr/lib/node_modules/istanbul/node_modules/esprima/esprima.js:3412:20)
    at inheritCoverGrammar (/usr/lib/node_modules/istanbul/node_modules/esprima/esprima.js:2679:18)
    at parsePostfixExpression (/usr/lib/node_modules/istanbul/node_modules/esprima/esprima.js:3488:16)
    at parseUnaryExpression (/usr/lib/node_modules/istanbul/node_modules/esprima/esprima.js:3548:20)
    at inheritCoverGrammar (/usr/lib/node_modules/istanbul/node_modules/esprima/esprima.js:2679:18)
    at parseBinaryExpression (/usr/lib/node_modules/istanbul/node_modules/esprima/esprima.js:3637:16)
    at inheritCoverGrammar (/usr/lib/node_modules/istanbul/node_modules/esprima/esprima.js:2679:18)
    at parseConditionalExpression (/usr/lib/node_modules/istanbul/node_modules/esprima/esprima.js:3694:16)
    at parseAssignmentExpression (/usr/lib/node_modules/istanbul/node_modules/esprima/esprima.js:3891:16)
    at isolateCoverGrammar (/usr/lib/node_modules/istanbul/node_modules/esprima/esprima.js:2661:18)
    at parseExpression (/usr/lib/node_modules/istanbul/node_modules/esprima/esprima.js:3940:16)
    at parseExpressionStatement (/usr/lib/node_modules/istanbul/node_modules/esprima/esprima.js:4220:20)
    at parseStatement (/usr/lib/node_modules/istanbul/node_modules/esprima/esprima.js:4758:24)
    at parseStatementListItem (/usr/lib/node_modules/istanbul/node_modules/esprima/esprima.js:3987:16)
    at parseScriptBody (/usr/lib/node_modules/istanbul/node_modules/esprima/esprima.js:5491:25)
    at parseProgram (/usr/lib/node_modules/istanbul/node_modules/esprima/esprima.js:5507:16)
    at Object.parse (/usr/lib/node_modules/istanbul/node_modules/esprima/esprima.js:5691:23)
    at Object.Instrumenter.instrumentSync (/usr/lib/node_modules/istanbul/lib/instrumenter.js:451:27)
    at /usr/lib/node_modules/istanbul/lib/command/common/run-with-cover.js:224:33
    at Array.forEach (native)
    at process.<anonymous> (/usr/lib/node_modules/istanbul/lib/command/common/run-with-cover.js:222:39)
    at process.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at process.emit (events.js:169:7)
    at process.exit (node.js:749:17)
    at done (/usr/lib/node_modules/mocha/bin/_mocha:406:32)
    at afterWrite (_stream_writable.js:346:3)
    at doNTCallbackMany (node.js:463:18)
    at process._tickCallback (node.js:361:17)
Build step 'Execute shell' marked build as failure
Recording test results
Started calculate disk usage of build
Finished Calculation of disk usage of build in 0 seconds
Started calculate disk usage of workspace
Finished Calculation of disk usage of workspace in  2 second
Finished: FAILURE
```

As far as I can tell after searching our code base, we're only using the `%` character in strings, or as the modulus operator. Any idea what's wrong here?
