### ISSUE TITLE
Does check-coverage read .istanbul.yml?

### ISSUE THREAD

**Issue by dsilva** [gotwarlost/istanbul#573]
If I have a reporting dir in my .istanbul.yml set to something like build/tmp/coverage, then "instanbul cover" will write to that directory but "instanbul check-coverage" won't read from it.

This can be worked around by passing build/tmp/coverage/*.json into the check-coverage command-line, but it would be best to avoid the duplication.

**Comment by guyellis** [comment]
The answer the question in the title of this issue is `yes` from what I've seen. I don't know if it reads everything though. I do know that it will read the `check/global` settings and apply them during check-coverage. You can test this by setting these at 100 and assuming that you don't have 100 coverage on the 4 attributes the check-coverage should fail.

e.g.:
```yaml
check:
    global:
        statements: 100
        lines: 100
        branches: 100
        functions: 100
        excludes: []
```

Also command line args override the settings in the file.
