### ISSUE TITLE
how to use check:each in config file ?

### ISSUE THREAD

**Issue by abenhamdine** [gotwarlost/istanbul#585]
Hi folks,

I would want to set coverage thresholds on a individual file basis, because of the legacy of the project, with some files not tested at all.
My use case is exactly the same as described in issue #30.

After read PR #268 and ```istanbul help config```, I'm confused about how to specify thresholds for specific files.

I tried to use the following config .istanbul.yml : 

```
check:
  global:
        statements: 10
        lines: 10
        branches: 10
        functions: 10
        excludes: ['src\HighTestedFile1.js']
  each:
        statements: 90
        lines: 90
        branches: 90
        functions: 90
        excludes: ['src\LowTestedFile1.js', 'src\LowTestedFile2.js]
```

Actually, it works.

But with these settings, I have only two thresholds of coverage : global and each (assuming the two excludes[] are complementary).
What if I want to set different threshold for some files ?

I tried to repeat the each block, and to play with the excludes[] property, like that : 

```
check:
  global:
        statements: 10
        lines: 10
        branches: 10
        functions: 10
        excludes: ['src\HighTestedFile1.js']
  each:
        statements: 90
        lines: 90
        branches: 90
        functions: 90
        excludes: ['src\VeryLowTestedFile1.js', 'src\LowTestedFile2.js]
  each:
        statements: 50
        lines: 50
        branches: 50
        functions: 50
        excludes: ['src\VeryLowTestedFile1.js', 'src\HighTestedFile1.js]
```

In addition to the complexity of the configuration, I find that it doesn't work : I get the following error message : 
```YAMLException: duplicated mapping key in "C:\node-projects\cvl-node-extdirect\.istanbul.yml"```

So did I miss something ? How to actually set individual check-coverage thresholds ?

Thx in advance for you help.

Tested on istanbul 0.4.2, nodejs 5.8.0, windows 7
