### ISSUE TITLE
file-matcher glob dependency

### ISSUE THREAD

**Issue by j0n4s** [gotwarlost/istanbul#685]
Error in file-matcher.js in called glob() if options.include is array with multiple files, for example [src/calculator.js src/calculator2.js src/obj-util.js], in callback don't return files, files return empty array... any idea how to resolve to return me the files?

**Comment by snypelife** [comment]
Same goes for if multiple file extensions are are set inside the .istanbul.yml file.
e.g.
```
instrumentation:
  extensions:
    - .js
    - .jsx
check:
  global:
    statements: 100
    lines: 100
    branches: 100
    functions: 100
```
