### ISSUE TITLE
Excludes configuration requires full path as of 0.4.5

### ISSUE THREAD

**Issue by src-code** [gotwarlost/istanbul#703]
As of 0.4.5, previous configuration of excludes will fail if the filename doesn't include a path.  For instance, for the file `util.js` in the directory `/lib/`:

```yml
instrumentation:
    excludes:
        - 'util.js'
```

Worked in 0.4.4 and earlier versions.  In 0.4.5, it no longer is applied.  The configuration must be updated to:

```yml
instrumentation:
    excludes:
        - 'lib/util.js'
```
